from __future__ import annotations

PLUGIN_NAME = "Underfed"
PLUGIN_VERSION = "0.3.2"
PLUGIN_DESCRIPTION = (
    "Moves a channel to its next source when the provider keeps delivering the stream, "
    "but at a fraction of the bitrate the content needs."
)

WATCHER_MODULE = "underfed.watcher"
RUN_TOKEN_ENV = "UNDERFED_RUN_TOKEN"
API_KEY_ENV = "UNDERFED_API_KEY"

DEFAULT_TELEMETRY_PATH = "/data/scripts/logs/delaybuf.log"
DEFAULT_API_URL = "http://127.0.0.1:9191"

DEFAULT_RATIO_PERCENT = 70
DEFAULT_CONFIRM_SECONDS = 45
DEFAULT_MAX_SWITCHES_PER_HOUR = 2
DEFAULT_WARMUP_SECONDS = 60
DEFAULT_STABLE_SECONDS = 180

MIN_TRUSTED_CRATE_MBPS = 0.5
SAMPLE_GAP_TOLERANCE_SECONDS = 45.0
INGEST_WINDOW_SECONDS = 45.0
INGEST_MIN_SPAN_SECONDS = 30.0

POLL_INTERVAL_SECONDS = 2.0
MAPPING_REFRESH_SECONDS = 900.0
API_TIMEOUT_SECONDS = 10.0
TERMINATE_GRACE_SECONDS = 10.0
HEARTBEAT_INTERVAL_SECONDS = 60.0

MAX_LOG_BYTES = 2 * 1024 * 1024
MAX_RECENT_EVENTS = 50
